Exposing flows(join_type) param
Flowminder/FlowKit pull request #4589
Opened 2021-11-22 15:49 UTC by Thingus

Closes #4586

### I have:

- [ ] Formatted any Python files with [black](https://github.com/ambv/black)
- [ ] Brought the branch up to date with master
- [ ] Added any relevant Github labels
- [ ] Added tests for any new additions
- [ ] Added or updated any relevant documentation
- [ ] Added an Architectural Decision Record (ADR), if appropriate
- [ ] Added an [MPLv2 License Header](https://www.mozilla.org/en-US/MPL/headers/) if appropriate
- [ ] Updated the [Changelog](https://github.com/Flowminder/FlowKit/blob/master/CHANGELOG.md) 

### Description

Exposes new join_type param

2021-11-22 17:31 UTC, jc-harrison requested changes
A couple of small changes here. Would be good to add (or modify) a couple of tests, too - see [test_queries.py](https://github.com/Flowminder/FlowKit/blob/master/integration_tests/tests/query_tests/test_queries.py) for integration tests to check that flowclient query schemas can be used to retrieve a result (probably sufficient to add a `join_type` param to one of the 'flows' cases there), and [test_query_object_construction.py](https://github.com/Flowminder/FlowKit/blob/master/flowmachine/tests/test_query_object_construction.py) for tests that query schemas deserialise to the expected queries.

2021-11-22 17:31 UTC, jc-harrison commented on flowmachine/flowmachine/core/server/query_schemas/flows.py
> +    join_type = fields.String(validate=OneOf(Flows.valid_joins))
Given that `Flows.valid_joins` isn't used within the Flows object, I think I'd prefer the list of valid joins to be directly specified here.

2021-11-22 17:31 UTC, jc-harrison commented on flowmachine/flowmachine/core/server/query_schemas/flows.py
> +    join_type = fields.String(validate=OneOf(Flows.valid_joins))
I'd also like to have either `required=True` (usually my preference) or `missing="inner"` (possibly preferable in this situation for backward compatibility) here.

2021-11-23 11:02 UTC, greenape commented on flowmachine/flowmachine/core/server/query_schemas/flows.py
> +    valid_joins = ("inner", "full outer", "left", "right", "left outer", "right outer")
This is == those valid for `Join`, right? Might make sense to put those there, and validate the input to join type (still want to validate it here of course).

2021-11-23 13:23 UTC, jc-harrison commented on flowclient/flowclient/aggregates.py
> +        Join type to use to build the flows
You'll need to also add this param description to the docstring of flowclient.aggregates.flows (the function that returns an API query object) - the arguments are automatically picked up from flows_spec, but unfortunately the docstring still needs to be manually duplicated.

2021-11-23 13:23 UTC, jc-harrison commented on flowmachine/flowmachine/core/server/query_schemas/flows.py
> +    def __init__(self, *, from_location, to_location, join_type=None):
You don't need the default `=None` here, since the schema ensures join_type is always present (and defaults to "inner" if not explicitly provided).

2021-11-23 15:15 UTC, jc-harrison approved these changes
As soon as the approval test expected results are updated, I'm happy with this.

2021-11-24 20:02 UTC, merged